#
# Module manifest for module 'SQLServerDscConfig'
#
# Generated by: Stu
#
# Generated on: 31/03/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ADControllerConfig.schema.psm1'

# Version number of this module.
ModuleVersion = '0.0.1.0'

# ID used to uniquely identify this module, generate new one via [GUID]::NewGuid()
GUID = 'd2730b09-7159-4067-8af9-8c54d17f1f26'

# Author of this module
Author = 'Stu (kewalaka@gmail.com)'

# Company or vendor of this module
CompanyName = 'N/A'

# Copyright statement for this module
Copyright = '(c) 2019 Stu. All rights reserved.'

# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @('PSDesiredStateConfiguration')

# DSC resources to export from this module
#DscResourcesToExport = @('Shared1')

}

